mybooksproject/mybooksapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='mybooksapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:booklist_id>/', views.detail_list, name='detail_list'),
    path('detail_book/<int:book_id>/', views.detail_book, name='detail_book'),
    path('new_book/', views.new_book, name='new_book'),
    path('delete_book/<int:book_id>/', views.delete_book, name='delete_book'),
    path('update_book/<int:book_id>', views.update_book, name='update_book'),
]

mybooksproject/mybooksproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mybooksapp/', include('mybooksapp.urls'))
]

mybooksproject/mybooksapp/models.py
from django.db import models

# Create your models here.

class BookList(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
            return f'{self.name}'

class BookGenre(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
            return f'{self.name}'

class Book(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    content = models.CharField(max_length=1500)
    rating = models.IntegerField(default=0, null=False)
    done = models.BooleanField(default=False, null=False)
    price = models.DecimalField(max_digits=7, decimal_places=2, default=0.00, null=False)
    cover = models.CharField(max_length=200)
    booklist = models.ForeignKey(BookList, on_delete=models.CASCADE)
    genre = models.ForeignKey(BookGenre, on_delete=models.CASCADE)

    def __str__(self):
            return f'{self.title} {self.author} {self.content} {self.rating} {self.done} {self.price} {self.cover} {self.booklist} {self.genre}'

mybooksproject/mybooksapp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import BookList, BookGenre, Book

def index(request):
    listen = BookList.objects.all()
    return render(request, 'mybooksapp/index.html', {'listen':listen})

def detail_list(request, booklist_id):
    liste = get_object_or_404(BookList, pk=booklist_id)
    books = Book.objects.filter(booklist=booklist_id)
    return render(request, 'mybooksapp/detail_list.html', {'liste':liste, 'books':books})

def detail_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'mybooksapp/detail_book.html', {'book':book})

# request.method == 'POST' gibt an, dass das Formular gesendet wurde(falls jemand etwas eingibt und auf speichern klickt!!) 
# request.POST : (zwischenspeicher) Formular mit den übermittelten/eingegebenen Daten.
# diese werden dann als neuer Wert an die jeweiligen Variablen weitergegen! title = request.POST...   

def new_book(request):
    if request.method == 'POST':
        title = request.POST["title"]
        author = request.POST["author"]
        content = request.POST["content"]
        rating = request.POST["rating"]
        price = request.POST["price"]
        cover = request.POST["cover"]
        booklist = BookList.objects.get(pk=request.POST["booklist"])
        genre = BookGenre.objects.get(pk=request.POST["genre"])
        Book.objects.create(title=title,
                            author=author,
                            content=content,
                            rating=rating,
                            price=price,
                            cover=cover,
                            booklist=booklist,
                            genre=genre,)
        return HttpResponseRedirect(reverse('mybooksapp:detail_list', args=[booklist.id]))

    return render(request, 'mybooksapp/new_book.html', {"booklists": BookList.objects.all(), "genres": BookGenre.objects.all()})

def delete_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    return HttpResponseRedirect(reverse('mybooksapp:index'))

def update_book_def(book, post):
    if "book_title" in post:
        book.title = post["book_title"]
    if "book_author" in post:
        book.author = post["book_author"]
    if "book_content" in post:
        book.content = post["book_content"]    
    if "book_rating" in post:
        try:
            rating = int(post["book_rating"]) 
        except ValueError:
            rating = 0
        book.rating = rating
    book.done = "book_done" in post
    if "book_price" in post:
        try:
            price = float(post["book_price"]) 
        except ValueError:
            price = 0
        book.price = price
    if "book_cover" in post:
        book.cover = post["book_cover"]
    if "book_booklist" in post:
        book.booklist = get_object_or_404(BookList, pk=post["book_booklist"])
    if "book_genre" in post:
        book.genre = get_object_or_404(BookGenre, pk=post["book_genre"])
    book.save()


def update_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.POST:
        update_book_def(book, request.POST)
        return HttpResponseRedirect(reverse('mybooksapp:detail_book', args=[book.id]))
    listen = BookList.objects.all()
    genres = BookGenre.objects.all()
    context = {
            "listen": listen, 
            "genres": genres, 
            "book": book, 
            }
    return render(request, "mybooksapp/update_book_def.html", context)

mybooksproject/mybooksapp/templates/mybooksapp/detail_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>{{book.title}}</title>
</head>
<body>
    <img src="{{book.cover}}" class="" alt="image">
    <table class='table'>
        <tr><th>Titel</th><th>Autor</th><th>Inhalt</th><th>Bewertung</th><th>Gelesen</th><th>Preis</th><th>Genre</th></tr>
        <tr>
            <td class='p-3'>{{book.title}}</td>
            <td class='p-3'>{{book.author}}</td>
            <td class='p-3'>{{book.content}}</td>
            <td class='p-3'>{{book.rating}}</td>
            <td class='p-3'>{{book.done}}</td>
            <td class='p-3'>{{book.price}}</td>
            <td class='p-3'>{{book.genre}}</td>
        </tr>
    </table>
    <a href="{% url 'mybooksapp:update_book' book.id%}">Bearbeiten</a>
    <a href="{% url 'mybooksapp:delete_book' book.id%}">Löschen</a>
</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/detail_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>{{liste.name}}</title>
</head>
<body>

    {%for book in books%}
        <div class="card" style="width: 10rem;">
            <img src="{{book.cover}}" class="card-img-top" alt="image">
            <div class="card-body">
                <h5 class="card-title">{{book.title}}</h5>
                <a href="{% url 'mybooksapp:detail_book' book.id%}" class="btn btn-primary">Detail</a>
            </div>
        </div>
    {%endfor%}

    <button type="button" class="btn btn-dark"><a href="{% url 'mybooksapp:new_book' %}" class='text-light'>+ Neues Buch hinzufügen</a></button>

</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>MyBooks</title>
</head>
<body>

    {% for list in listen%}
        <a href="{% url 'mybooksapp:detail_list' list.id%}">{{ list.name }}</a>
    {% endfor %}

</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/new_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Neues Buch hinzufügen</title>
</head>
<body>

    <form action="" method="post">
    {% csrf_token %}
    <label>Titel</label><input type="text" name="title">
    <label>Autor:in</label><input type="text" name="author">
    <label>Inhalt</label><input type="textarea" name="content">
    <label>Bewertung</label><input type="number" name="rating">
    <label>Preis</label></br><input type="number" step="0.01" name="price">
    <label>Cover</label><input type="text" name="cover">
    <label>Shopping Liste</label></br>
    <select name="booklist">
      {% for list in booklists %}
        <option value="{{list.id}}">{{list}}</option>
      {% endfor %}
    </select>
    <select name="genre">
      {% for genre in genres %}
        <option value="{{genre.id}}">{{genre}}</option>
      {% endfor %}
    </select>

    <input type="submit" class="btn mt-4" value="Anlegen">
  </form>

</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/update_book_def.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Buch bearbeitem</title>
</head>
<body>

    <form action="{% url 'mybooksapp:update_book' book.id %}" method="POST">
    <div class="form-group">
        {% csrf_token %}
        <label for="book_title">Titel</label>
        <input class="form-control" type="text" name="book_title" id="book_title" value="{{book.title}}"><br>

        <label for="book_author">Autor</label>
        <input class="form-control" type="text" name="book_author" id="book_author" value="{{book.author}}"><br>

        <label for="book_content">Inhalt</label>
        <input class="form-control" type="text" name="book_content" id="book_content" value="{{book.content}}"><br>

        <label for="book_rating">Bewertung</label>
        <input class="form-control" type="number" name="book_rating" id="book_rating" value="{{book.rating}}"><br>

        <label for="book_done">Gelesen</label>
        <input class="form-check" type="checkbox" name="book_done" id="book_done" value="{{book.done}}" {% if book.done %}checked{% endif %}><br>

        <label for="book_price">Preis</label>
        <input class="form-control" type="number" step="0.01" name="book_price" id="book_price" value="{{book.price}}"><br>

        <label for="book_cover">Cover</label>
        <input class="form-control" type="text" name="book_cover" id="book_cover" value="{{book.cover}}"><br>

        <label for="book_booklist">Liste</label>
        <select class="form-control" name="book_booklist" id="book_booklist">
        {% for liste in listen %}
        <option value="{{liste.id}}" {% if liste == book.liste %}selected{% endif %}>{{liste.name}}</option> 
        {% endfor %}  
        </select><br>

        <label for="book_genre">Genre</label>
        <select class="form-control" name="book_genre" id="book_genre">
        {% for genre in genres %}
        <option value="{{genre.id}}" {% if genre == book.genre %}selected{% endif %}>{{genre.name}}</option> 
        {% endfor %}  
        </select><br>

        <div class="input-group">
        <input class="btn btn-primary" type="submit" value="Speichern">
        </div>
    </div>
    </form>


</body>
</html>